SITE:
  TITLE: CLIENT CREDENTIALS EXAMPLE

IDENTITY:
  APP_ID: "exampleAppName"
  URL: "tenant.my.idaptive.app"
  CLIENT_ID: "identity-privilege-integration-user$@example.com"
  CLIENT_SECRET: "ExampleSecret12!@"