name: Go

on:
  push:
    branches: [ main, 9-add-tests-for-various-functions ]
  pull_request:
    branches: [ main, 9-add-tests-for-various-functions ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18

    - name: Test
      run: go test -v ./...
